// flow-typed signature: 8fdea89bc9666acb48341695ef9aa7d3
// flow-typed version: <<STUB>>/react-hook-form_v^7.18.0/flow_v0.163.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-hook-form'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-hook-form' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-hook-form/dist/index.cjs' {
  declare module.exports: any;
}

declare module 'react-hook-form/dist/index.esm' {
  declare module.exports: any;
}

declare module 'react-hook-form/dist/index.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-hook-form/dist/index.cjs.js' {
  declare module.exports: $Exports<'react-hook-form/dist/index.cjs'>;
}
declare module 'react-hook-form/dist/index.esm.js' {
  declare module.exports: $Exports<'react-hook-form/dist/index.esm'>;
}
declare module 'react-hook-form/dist/index.umd.js' {
  declare module.exports: $Exports<'react-hook-form/dist/index.umd'>;
}
