// flow-typed signature: 545643a14df0bcd1e7e7077a9f58eb0a
// flow-typed version: <<STUB>>/@hookform/resolvers_v^2.8.2/flow_v0.163.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@hookform/resolvers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@hookform/resolvers' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@hookform/resolvers/class-validator/dist/class-validator' {
  declare module.exports: any;
}

declare module '@hookform/resolvers/class-validator/dist/class-validator.modern' {
  declare module.exports: any;
}

declare module '@hookform/resolvers/class-validator/dist/class-validator.module' {
  declare module.exports: any;
}

declare module '@hookform/resolvers/class-validator/dist/class-validator.umd' {
  declare module.exports: any;
}

declare module '@hookform/resolvers/computed-types/dist/computed-types' {
  declare module.exports: any;
}

declare module '@hookform/resolvers/computed-types/dist/computed-types.modern' {
  declare module.exports: any;
}

declare module '@hookform/resolvers/computed-types/dist/computed-types.module' {
  declare module.exports: any;
}

declare module '@hookform/resolvers/computed-types/dist/computed-types.umd' {
  declare module.exports: any;
}

declare module '@hookform/resolvers/dist/resolvers' {
  declare module.exports: any;
}

declare module '@hookform/resolvers/dist/resolvers.module' {
  declare module.exports: any;
}

declare module '@hookform/resolvers/dist/resolvers.umd' {
  declare module.exports: any;
}

declare module '@hookform/resolvers/io-ts/dist/io-ts' {
  declare module.exports: any;
}

declare module '@hookform/resolvers/io-ts/dist/io-ts.modern' {
  declare module.exports: any;
}

declare module '@hookform/resolvers/io-ts/dist/io-ts.module' {
  declare module.exports: any;
}

declare module '@hookform/resolvers/io-ts/dist/io-ts.umd' {
  declare module.exports: any;
}

declare module '@hookform/resolvers/joi/dist/joi' {
  declare module.exports: any;
}

declare module '@hookform/resolvers/joi/dist/joi.modern' {
  declare module.exports: any;
}

declare module '@hookform/resolvers/joi/dist/joi.module' {
  declare module.exports: any;
}

declare module '@hookform/resolvers/joi/dist/joi.umd' {
  declare module.exports: any;
}

declare module '@hookform/resolvers/nope/dist/nope' {
  declare module.exports: any;
}

declare module '@hookform/resolvers/nope/dist/nope.modern' {
  declare module.exports: any;
}

declare module '@hookform/resolvers/nope/dist/nope.module' {
  declare module.exports: any;
}

declare module '@hookform/resolvers/nope/dist/nope.umd' {
  declare module.exports: any;
}

declare module '@hookform/resolvers/superstruct/dist/superstruct' {
  declare module.exports: any;
}

declare module '@hookform/resolvers/superstruct/dist/superstruct.modern' {
  declare module.exports: any;
}

declare module '@hookform/resolvers/superstruct/dist/superstruct.module' {
  declare module.exports: any;
}

declare module '@hookform/resolvers/superstruct/dist/superstruct.umd' {
  declare module.exports: any;
}

declare module '@hookform/resolvers/typanion/dist/typanion' {
  declare module.exports: any;
}

declare module '@hookform/resolvers/typanion/dist/typanion.modern' {
  declare module.exports: any;
}

declare module '@hookform/resolvers/typanion/dist/typanion.module' {
  declare module.exports: any;
}

declare module '@hookform/resolvers/typanion/dist/typanion.umd' {
  declare module.exports: any;
}

declare module '@hookform/resolvers/vest/dist/vest' {
  declare module.exports: any;
}

declare module '@hookform/resolvers/vest/dist/vest.modern' {
  declare module.exports: any;
}

declare module '@hookform/resolvers/vest/dist/vest.module' {
  declare module.exports: any;
}

declare module '@hookform/resolvers/vest/dist/vest.umd' {
  declare module.exports: any;
}

declare module '@hookform/resolvers/yup/dist/yup' {
  declare module.exports: any;
}

declare module '@hookform/resolvers/yup/dist/yup.modern' {
  declare module.exports: any;
}

declare module '@hookform/resolvers/yup/dist/yup.module' {
  declare module.exports: any;
}

declare module '@hookform/resolvers/yup/dist/yup.umd' {
  declare module.exports: any;
}

declare module '@hookform/resolvers/zod/dist/zod' {
  declare module.exports: any;
}

declare module '@hookform/resolvers/zod/dist/zod.modern' {
  declare module.exports: any;
}

declare module '@hookform/resolvers/zod/dist/zod.module' {
  declare module.exports: any;
}

declare module '@hookform/resolvers/zod/dist/zod.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module '@hookform/resolvers/class-validator/dist/class-validator.js' {
  declare module.exports: $Exports<'@hookform/resolvers/class-validator/dist/class-validator'>;
}
declare module '@hookform/resolvers/class-validator/dist/class-validator.modern.js' {
  declare module.exports: $Exports<'@hookform/resolvers/class-validator/dist/class-validator.modern'>;
}
declare module '@hookform/resolvers/class-validator/dist/class-validator.module.js' {
  declare module.exports: $Exports<'@hookform/resolvers/class-validator/dist/class-validator.module'>;
}
declare module '@hookform/resolvers/class-validator/dist/class-validator.umd.js' {
  declare module.exports: $Exports<'@hookform/resolvers/class-validator/dist/class-validator.umd'>;
}
declare module '@hookform/resolvers/computed-types/dist/computed-types.js' {
  declare module.exports: $Exports<'@hookform/resolvers/computed-types/dist/computed-types'>;
}
declare module '@hookform/resolvers/computed-types/dist/computed-types.modern.js' {
  declare module.exports: $Exports<'@hookform/resolvers/computed-types/dist/computed-types.modern'>;
}
declare module '@hookform/resolvers/computed-types/dist/computed-types.module.js' {
  declare module.exports: $Exports<'@hookform/resolvers/computed-types/dist/computed-types.module'>;
}
declare module '@hookform/resolvers/computed-types/dist/computed-types.umd.js' {
  declare module.exports: $Exports<'@hookform/resolvers/computed-types/dist/computed-types.umd'>;
}
declare module '@hookform/resolvers/dist/resolvers.js' {
  declare module.exports: $Exports<'@hookform/resolvers/dist/resolvers'>;
}
declare module '@hookform/resolvers/dist/resolvers.module.js' {
  declare module.exports: $Exports<'@hookform/resolvers/dist/resolvers.module'>;
}
declare module '@hookform/resolvers/dist/resolvers.umd.js' {
  declare module.exports: $Exports<'@hookform/resolvers/dist/resolvers.umd'>;
}
declare module '@hookform/resolvers/io-ts/dist/io-ts.js' {
  declare module.exports: $Exports<'@hookform/resolvers/io-ts/dist/io-ts'>;
}
declare module '@hookform/resolvers/io-ts/dist/io-ts.modern.js' {
  declare module.exports: $Exports<'@hookform/resolvers/io-ts/dist/io-ts.modern'>;
}
declare module '@hookform/resolvers/io-ts/dist/io-ts.module.js' {
  declare module.exports: $Exports<'@hookform/resolvers/io-ts/dist/io-ts.module'>;
}
declare module '@hookform/resolvers/io-ts/dist/io-ts.umd.js' {
  declare module.exports: $Exports<'@hookform/resolvers/io-ts/dist/io-ts.umd'>;
}
declare module '@hookform/resolvers/joi/dist/joi.js' {
  declare module.exports: $Exports<'@hookform/resolvers/joi/dist/joi'>;
}
declare module '@hookform/resolvers/joi/dist/joi.modern.js' {
  declare module.exports: $Exports<'@hookform/resolvers/joi/dist/joi.modern'>;
}
declare module '@hookform/resolvers/joi/dist/joi.module.js' {
  declare module.exports: $Exports<'@hookform/resolvers/joi/dist/joi.module'>;
}
declare module '@hookform/resolvers/joi/dist/joi.umd.js' {
  declare module.exports: $Exports<'@hookform/resolvers/joi/dist/joi.umd'>;
}
declare module '@hookform/resolvers/nope/dist/nope.js' {
  declare module.exports: $Exports<'@hookform/resolvers/nope/dist/nope'>;
}
declare module '@hookform/resolvers/nope/dist/nope.modern.js' {
  declare module.exports: $Exports<'@hookform/resolvers/nope/dist/nope.modern'>;
}
declare module '@hookform/resolvers/nope/dist/nope.module.js' {
  declare module.exports: $Exports<'@hookform/resolvers/nope/dist/nope.module'>;
}
declare module '@hookform/resolvers/nope/dist/nope.umd.js' {
  declare module.exports: $Exports<'@hookform/resolvers/nope/dist/nope.umd'>;
}
declare module '@hookform/resolvers/superstruct/dist/superstruct.js' {
  declare module.exports: $Exports<'@hookform/resolvers/superstruct/dist/superstruct'>;
}
declare module '@hookform/resolvers/superstruct/dist/superstruct.modern.js' {
  declare module.exports: $Exports<'@hookform/resolvers/superstruct/dist/superstruct.modern'>;
}
declare module '@hookform/resolvers/superstruct/dist/superstruct.module.js' {
  declare module.exports: $Exports<'@hookform/resolvers/superstruct/dist/superstruct.module'>;
}
declare module '@hookform/resolvers/superstruct/dist/superstruct.umd.js' {
  declare module.exports: $Exports<'@hookform/resolvers/superstruct/dist/superstruct.umd'>;
}
declare module '@hookform/resolvers/typanion/dist/typanion.js' {
  declare module.exports: $Exports<'@hookform/resolvers/typanion/dist/typanion'>;
}
declare module '@hookform/resolvers/typanion/dist/typanion.modern.js' {
  declare module.exports: $Exports<'@hookform/resolvers/typanion/dist/typanion.modern'>;
}
declare module '@hookform/resolvers/typanion/dist/typanion.module.js' {
  declare module.exports: $Exports<'@hookform/resolvers/typanion/dist/typanion.module'>;
}
declare module '@hookform/resolvers/typanion/dist/typanion.umd.js' {
  declare module.exports: $Exports<'@hookform/resolvers/typanion/dist/typanion.umd'>;
}
declare module '@hookform/resolvers/vest/dist/vest.js' {
  declare module.exports: $Exports<'@hookform/resolvers/vest/dist/vest'>;
}
declare module '@hookform/resolvers/vest/dist/vest.modern.js' {
  declare module.exports: $Exports<'@hookform/resolvers/vest/dist/vest.modern'>;
}
declare module '@hookform/resolvers/vest/dist/vest.module.js' {
  declare module.exports: $Exports<'@hookform/resolvers/vest/dist/vest.module'>;
}
declare module '@hookform/resolvers/vest/dist/vest.umd.js' {
  declare module.exports: $Exports<'@hookform/resolvers/vest/dist/vest.umd'>;
}
declare module '@hookform/resolvers/yup/dist/yup.js' {
  declare module.exports: $Exports<'@hookform/resolvers/yup/dist/yup'>;
}
declare module '@hookform/resolvers/yup/dist/yup.modern.js' {
  declare module.exports: $Exports<'@hookform/resolvers/yup/dist/yup.modern'>;
}
declare module '@hookform/resolvers/yup/dist/yup.module.js' {
  declare module.exports: $Exports<'@hookform/resolvers/yup/dist/yup.module'>;
}
declare module '@hookform/resolvers/yup/dist/yup.umd.js' {
  declare module.exports: $Exports<'@hookform/resolvers/yup/dist/yup.umd'>;
}
declare module '@hookform/resolvers/zod/dist/zod.js' {
  declare module.exports: $Exports<'@hookform/resolvers/zod/dist/zod'>;
}
declare module '@hookform/resolvers/zod/dist/zod.modern.js' {
  declare module.exports: $Exports<'@hookform/resolvers/zod/dist/zod.modern'>;
}
declare module '@hookform/resolvers/zod/dist/zod.module.js' {
  declare module.exports: $Exports<'@hookform/resolvers/zod/dist/zod.module'>;
}
declare module '@hookform/resolvers/zod/dist/zod.umd.js' {
  declare module.exports: $Exports<'@hookform/resolvers/zod/dist/zod.umd'>;
}
